# Generated by Django 4.0.3 on 2022-03-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.JSONField(help_text='Array of annotator votes', verbose_name='votes')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator', models.CharField(help_text='Annotator that will make the vote', max_length=100)),
                ('vote', models.CharField(help_text='Vote that the annotator did', max_length=100)),
                ('counter', models.BigIntegerField(default=1)),
            ],
        ),
    ]
