# Generated by Django 4.0.3 on 2022-03-25 05:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='votes',
            field=models.JSONField(default=list, help_text='Array of annotator votes', validators=[core.validators.JSONSchemaValidator(limit_value={'$id': 'https://example.com/object1648177539.json', '$schema': 'http://json-schema.org/draft-07/schema#', 'default': [], 'definitions': {}, 'items': {'$id': '#root/items', 'properties': {'annotator': {'$id': '#root/items/annotator', 'default': '', 'examples': ['vote'], 'pattern': '^.*$', 'title': 'Annotator', 'type': 'string'}}, 'title': 'Items', 'type': 'object'}, 'title': 'Root', 'type': 'array'})], verbose_name='votes'),
        ),
    ]
